#create interrupt functions for aurix spi module
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/../main/drivers/bus_spi_tc375_int.c"

# Overwrite output file
cat > "${OUTPUT_FILE}" <<EOF
//this file is generated by aurix_generate_spi_isr.sh. Changes will be overwritten!
#pragma once

#include <platform.h>
#include "drivers/bus_spi.h"
#include "build/build_config.h"

EOF

# add more SPI buses if needed
for DEV in 1 2 3 4; do
    QSPI_INDEX=$((DEV - 1))

    cat >> "${OUTPUT_FILE}" <<EOF
#ifdef USE_SPI_DEVICE_${DEV}
extern SpiBus_t SPI${DEV};
EOF

    # add more CPU cores if needed
    for CPU in 0 1 2; do
        cat >> "${OUTPUT_FILE}" <<EOF

/* CPU ${CPU} */
IFX_INTERRUPT(qspi${QSPI_INDEX}TxISR${CPU}, ${CPU}, INTPRIO_QSPI${QSPI_INDEX}_TX);
void CPU${CPU}_PSPR_FUNCTION qspi${QSPI_INDEX}TxISR${CPU}(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI${DEV}.spiMaster));
}
IFX_INTERRUPT(qspi${QSPI_INDEX}RxISR${CPU}, ${CPU}, INTPRIO_QSPI${QSPI_INDEX}_RX);
void CPU${CPU}_PSPR_FUNCTION qspi${QSPI_INDEX}RxISR${CPU}(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI${DEV}.spiMaster));
}
EOF
    done

    cat >> "${OUTPUT_FILE}" <<EOF
#endif
EOF
done

echo "Generated ${OUTPUT_FILE}"
