//this file is generated by aurix_generate_spi_isr.sh. Changes will be overwritten!

#include <platform.h>
#include "drivers/bus_spi.h"
#include "build/build_config.h"

#ifdef USE_SPI_DEVICE_1
extern SpiBus_t SPI1;

/* CPU 0 */
IFX_INTERRUPT(qspi0TxISR0, 0, INTPRIO_QSPI0_TX);
void CPU0_PSPR_FUNCTION qspi0TxISR0(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI1.spiMaster));
}
IFX_INTERRUPT(qspi0RxISR0, 0, INTPRIO_QSPI0_RX);
void CPU0_PSPR_FUNCTION qspi0RxISR0(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI1.spiMaster));
}

/* CPU 1 */
IFX_INTERRUPT(qspi0TxISR1, 1, INTPRIO_QSPI0_TX);
void CPU1_PSPR_FUNCTION qspi0TxISR1(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI1.spiMaster));
}
IFX_INTERRUPT(qspi0RxISR1, 1, INTPRIO_QSPI0_RX);
void CPU1_PSPR_FUNCTION qspi0RxISR1(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI1.spiMaster));
}

/* CPU 2 */
IFX_INTERRUPT(qspi0TxISR2, 2, INTPRIO_QSPI0_TX);
void CPU2_PSPR_FUNCTION qspi0TxISR2(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI1.spiMaster));
}
IFX_INTERRUPT(qspi0RxISR2, 2, INTPRIO_QSPI0_RX);
void CPU2_PSPR_FUNCTION qspi0RxISR2(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI1.spiMaster));
}
#endif
#ifdef USE_SPI_DEVICE_2
extern SpiBus_t SPI2;

/* CPU 0 */
IFX_INTERRUPT(qspi1TxISR0, 0, INTPRIO_QSPI1_TX);
void CPU0_PSPR_FUNCTION qspi1TxISR0(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI2.spiMaster));
}
IFX_INTERRUPT(qspi1RxISR0, 0, INTPRIO_QSPI1_RX);
void CPU0_PSPR_FUNCTION qspi1RxISR0(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI2.spiMaster));
}

/* CPU 1 */
IFX_INTERRUPT(qspi1TxISR1, 1, INTPRIO_QSPI1_TX);
void CPU1_PSPR_FUNCTION qspi1TxISR1(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI2.spiMaster));
}
IFX_INTERRUPT(qspi1RxISR1, 1, INTPRIO_QSPI1_RX);
void CPU1_PSPR_FUNCTION qspi1RxISR1(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI2.spiMaster));
}

/* CPU 2 */
IFX_INTERRUPT(qspi1TxISR2, 2, INTPRIO_QSPI1_TX);
void CPU2_PSPR_FUNCTION qspi1TxISR2(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI2.spiMaster));
}
IFX_INTERRUPT(qspi1RxISR2, 2, INTPRIO_QSPI1_RX);
void CPU2_PSPR_FUNCTION qspi1RxISR2(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI2.spiMaster));
}
#endif
#ifdef USE_SPI_DEVICE_3
extern SpiBus_t SPI3;

/* CPU 0 */
IFX_INTERRUPT(qspi2TxISR0, 0, INTPRIO_QSPI2_TX);
void CPU0_PSPR_FUNCTION qspi2TxISR0(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI3.spiMaster));
}
IFX_INTERRUPT(qspi2RxISR0, 0, INTPRIO_QSPI2_RX);
void CPU0_PSPR_FUNCTION qspi2RxISR0(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI3.spiMaster));
}

/* CPU 1 */
IFX_INTERRUPT(qspi2TxISR1, 1, INTPRIO_QSPI2_TX);
void CPU1_PSPR_FUNCTION qspi2TxISR1(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI3.spiMaster));
}
IFX_INTERRUPT(qspi2RxISR1, 1, INTPRIO_QSPI2_RX);
void CPU1_PSPR_FUNCTION qspi2RxISR1(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI3.spiMaster));
}

/* CPU 2 */
IFX_INTERRUPT(qspi2TxISR2, 2, INTPRIO_QSPI2_TX);
void CPU2_PSPR_FUNCTION qspi2TxISR2(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI3.spiMaster));
}
IFX_INTERRUPT(qspi2RxISR2, 2, INTPRIO_QSPI2_RX);
void CPU2_PSPR_FUNCTION qspi2RxISR2(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI3.spiMaster));
}
#endif
#ifdef USE_SPI_DEVICE_4
extern SpiBus_t SPI4;

/* CPU 0 */
IFX_INTERRUPT(qspi3TxISR0, 0, INTPRIO_QSPI3_TX);
void CPU0_PSPR_FUNCTION qspi3TxISR0(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI4.spiMaster));
}
IFX_INTERRUPT(qspi3RxISR0, 0, INTPRIO_QSPI3_RX);
void CPU0_PSPR_FUNCTION qspi3RxISR0(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI4.spiMaster));
}

/* CPU 1 */
IFX_INTERRUPT(qspi3TxISR1, 1, INTPRIO_QSPI3_TX);
void CPU1_PSPR_FUNCTION qspi3TxISR1(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI4.spiMaster));
}
IFX_INTERRUPT(qspi3RxISR1, 1, INTPRIO_QSPI3_RX);
void CPU1_PSPR_FUNCTION qspi3RxISR1(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI4.spiMaster));
}

/* CPU 2 */
IFX_INTERRUPT(qspi3TxISR2, 2, INTPRIO_QSPI3_TX);
void CPU2_PSPR_FUNCTION qspi3TxISR2(void){
    IfxQspi_SpiMaster_isrTransmit(&(SPI4.spiMaster));
}
IFX_INTERRUPT(qspi3RxISR2, 2, INTPRIO_QSPI3_RX);
void CPU2_PSPR_FUNCTION qspi3RxISR2(void){
    IfxQspi_SpiMaster_isrReceive(&(SPI4.spiMaster));
}
#endif
